name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 0 */3 * *'  # يتم التنفيذ تلقائياً كل 3 أيام
  workflow_dispatch:      # يتيح لك تشغيله يدوياً بأي وقت

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Auto Update
        run: |
          date > keepalive.txt
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add keepalive.txt
          git commit -m "Keep alive Streamlit" || exit 0
          git push
